annotations:
  artifacthub.io/containsSecurityUpdates: "true"
apiVersion: v2
appVersion: V1.0
description: 'Het WRC bevat de resources die nodig zijn voor het draaien van een applicatie, zoals sjablonen, routing, menu’s en afbeeldingen. Het heeft hierbij de doelstelling om te fungeren als een “headless CMS” ofwel een CMS als API die losstaat van enige vorm van weergave. Voor het bewerken van de CMS content leunt het WRC dan ook op het Dashboard (een implementatie van de Proto Applicatie), en het fungeert zelf als een bron voor een applicatie.'
name: webresourcecatalogus
version: 1.1.0
home: https://www.conduction.nl
icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
sources:
  - https://commonground.conduction.nl/
  - https://www.commonground.nl/
keywords:
  - commonground
  - haven
  - nlx
  - component
maintainers:
  - email: ruben@conduction.nl
    name: Ruben van der Linde
  - email: info@conduction.nl
    name: Conduction
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 10.10.3
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 12.7.7
    condition: redis.enabled
