apiVersion: v1
entries:
  wrc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-08-04T08:22:10.940485017Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: c21c1894a36111228842541e3b16f657ca5409bf785681a39ffa6e5d53747ac3
    home: wrc.zaakonline.nl
    icon: wrc.zaakonline.nl
    name: wrc
    urls:
    - wrc-0.1.0.tgz
    version: 0.1.0
generated: "2020-08-04T08:22:10.924356218Z"
