apiVersion: v1
entries:
  pc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-07-20T08:15:39.696448967Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: a3ebf537582710b118b706a276db61fec8e25b642f3e8f3d1bb239ac1131f064
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: pc
    urls:
    - pc-0.1.0.tgz
    version: 0.1.0
  wrc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-07-20T08:15:39.699810867Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: eff79aaa57dbf00d0070469455e2ceb4c4b8501bdba242b240cec96dff17032a
    home: wrc.zaakonline.nl
    icon: wrc.zaakonline.nl
    name: wrc
    urls:
    - wrc-0.1.0.tgz
    version: 0.1.0
generated: "2020-07-20T08:15:39.693232367Z"
