apiVersion: v1
entries:
  wrc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-08-04T08:12:06.280207937Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: b7f757e8d6df4dfd5ad1c9e146a86f54b2fa629b4ea9c5963f2a2dcfa5c32a30
    home: wrc.zaakonline.nl
    icon: wrc.zaakonline.nl
    name: wrc
    urls:
    - wrc-0.1.0.tgz
    version: 0.1.0
generated: "2020-08-04T08:12:06.273059737Z"
