apiVersion: v1
entries:
  wrc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-07-31T14:29:35.848929195Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: acd650c96682ed327eb95114b06589c4c5fca647a2f76a2d03cb2485eac29a1c
    home: wrc.zaakonline.nl
    icon: wrc.zaakonline.nl
    name: wrc
    urls:
    - wrc-0.1.0.tgz
    version: 0.1.0
generated: "2020-07-31T14:29:35.835580695Z"
