apiVersion: v1
entries:
  wrc:
  - apiVersion: v1
    appVersion: V.0.1
<<<<<<< Updated upstream
    created: "2020-06-24T11:55:14.028357644Z"
=======
    created: "2020-06-24T12:20:31.900314955Z"
>>>>>>> Stashed changes
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 7daf26318c451de7bbcbe9f7d394655d7b27a3ec717788758e0e1287d9f1ab44
    home: wrc.zaakonline.nl
    icon: wrc.zaakonline.nl
    name: wrc
    urls:
    - wrc-0.1.0.tgz
    version: 0.1.0
<<<<<<< Updated upstream
generated: "2020-06-24T11:55:14.018524045Z"
=======
generated: "2020-06-24T12:20:31.896975356Z"
>>>>>>> Stashed changes
