apiVersion: v1
kind: Service
metadata:
  name: {{ include "webresourcecatalogus.fullname" . }}
  labels:
    {{- include "webresourcecatalogus.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations}}
    {{- toYaml | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 80
      protocol: TCP
      name: https
  selector:
    {{- include "webresourcecatalogus.selectorLabels" . | nindent 4 }}
